
# Refer to https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html for env args
version: "3.9" 
services:
  modsim-base:
    ports:
      - '8888:8888'
      - '8889:8889'
      - '1111:22'
    dns:
      - 8.8.8.8
    user: root
    environment:
      - NB_USER=jovyan
      - CHOWN_HOME=yes
      - CHOWN_EXTRA=content
      - DOCKER_STACKS_JUPYTER_CMD=nbclassic
    volumes:
      - ../content:/home/jovyan/content
    #image: ghcr.io/anaegel/modsim-course-python:latest
    image: anaegel/vtkexp	
#volumes:
#  myFiles:
#    external: true
